package padroesestruturais.adapter;

public class ContaAdapter extends TipoConta{

    private Conta poupanca;

    public Conta (Conta TipocontaPoupanca) {
        this.TipocontaPoupanca = TipocontaPoupanca;
    }

    public String recuperarConta() {
        if (this.getConta()
           TipocontaPoupanca.setConta("A");


    public void salvarConta() {
        if (TipoConta.getConta().equals("A"))
            this.setConta
       